### ISSUE TITLE
missing build file .deb in release note?

### ISSUE THREAD

**Issue by quocle108** [AntelopeIO/DUNE#100]
> ### DUNE installation on Linux <a name="dune-linux"></a>
> 
> This is the fastest way to get started. From the [latest release](https://github.com/AntelopeIO/DUNE/releases/latest) page, download DUNE `*.deb` file or visit the [release tags](https://github.com/AntelopeIO/DUNE/releases) page to download specific version of DUNE deb package.
> 

As far as i didn't see *.deb in https://github.com/AntelopeIO/DUNE/releases/latest. any missing here?

**Comment by quocle108** [comment]
then how can I run DUNE? I was going through the Readme but not sure how I can run DUNE without the deb. Better to make a QuickStart in Readme.

**Comment by mikelik** [comment]
> then how can I run DUNE? I was going through the Readme but not sure how I can run DUNE without the deb. Better to make a QuickStart in Readme.

We are preparing the new release with deb file. In the meanwhile can you please follow the old README:
https://github.com/AntelopeIO/DUNE/blob/c66f1a54b8b3bda0f25e7918e924a9e048ac0e84/README.md

In short you need to clone repo and start using `dune` command. I think running `bootstrap.sh`, which rebuild the docker image, is optional now as the image will be automatically downloaded.

**Comment by stephenpdeos** [comment]
This will be resolved with the next DUNE release targeted for sometime next week.

**Comment by mikelik** [comment]
DUNE 1.1.0 has been released together with .deb package.
