### ISSUE TITLE
Change .Net to 4.8 to pass the Chocolatey verification

### ISSUE THREAD

**Issue by mikelik** [AntelopeIO/DUNE#109]
After pushing DUNE 1.1.0 to Chocolatey repository:
https://community.chocolatey.org/packages/antelopeio-dune/1.1.0
the following issue happens:
`2023-01-27 12:38:38,587 3708 [DEBUG] - Caught System.Management.Automation.RuntimeException with message = [Running ["C:\Users\vagrant\AppData\Local\Temp\chocolatey\dotnetfx\4.8.1.0-rtw\ndp481-x86-x64-allos-enu.exe" /Quiet /NoRestart /Log "C:\Users\vagrant\AppData\Local\Temp\chocolatey\dotnetfx_4.8.1_20230127123809.log" ] was not successful. Exit code was '5100'.`
(logs from https://gist.github.com/choco-bot/ee8de040a78520e871a81aa30e9307c4)

The effect is that our DUNE package is not officially available, because it was not automatically verified.

**Solution:**
It looks like it is trying to install .Net 4.8.1, which is not compatible with server 2019 (which is what is running on the package verifier).
I'd suggest switching over to taking a dependency on the netfx-4.8 package. https://community.chocolatey.org/packages/netfx-4.8

**Comment by stephenpdeos** [comment]
Holding off for now since this may be a shared issue with others submitting to Chocolatey. Will revisit in the next few weeks.

**Comment by mikelik** [comment]
Solution which work for others:
"It looks like it is trying to install .Net 4.8.1, which is not compatible with server 2019 (which is what is running on the package verifier).
I'd suggest switching over to taking a dependency on the netfx-4.8 package. https://community.chocolatey.org/packages/netfx-4.8"

**Comment by mikelik** [comment]
The change would be to add one dependency to .net 4.8 in the following file: https://github.com/AntelopeIO/DUNE/blob/main/packaging/antelopeio-dune/antelopeio-dune.nuspec (1 hour)
submitting it to Chocolatey repo (1 hour for first time set up) and waiting for the results (~6 hours) done by Chocolate automated scripts (they are e-mailing results to support at eosnetwork dot com).
In total this should take 1 day assuming no mistakes are made.
