### ISSUE TITLE
System is not initialized after bootstrap-system-full

### ISSUE THREAD

**Issue by nsjames** [AntelopeIO/DUNE#112]
After running the `--bootstrap-system-full` command, accounts can no longer be created as the chain has not been initialized. 

![image](https://user-images.githubusercontent.com/10360675/218686828-6b261dd4-5ded-44d5-ab28-57947d966d46.png)

More information from Michal: 
```
When I run command dune -- cleos push action eosio init '[0,"4,SYS"]' -p eosio@active it says Unknown action init in contract eosio
```

**Comment by mikelik** [comment]
Above command `cleos push action eosio init` comes from old documentation, where this issue happened: https://developers.eos.io/manuals/eosio.cdt/v1.8/troubleshooting/index/#assertion-failure-while-creating-an-account-after-eosiosystem-was-installed
