### ISSUE TITLE
DUNE - invalid help for some of the options

### ISSUE THREAD

**Issue by mikelik** [AntelopeIO/DUNE#123]
When executing `dune --help` we get:
```
--create-account ['NAME', 'CREATOR (Optional)', 'PUB_KEY (Optional)', 'PRIV_KEY (Optional)'] [['NAME', 'CREATOR (Optional)', 'PUB_KEY (Optional)', 'PRIV_KEY (Optional)'] ...]
                        create an EOSIO account and an optional creator (the default is eosio)
  --system-newaccount ['NAME', 'CREATOR (Optional)', 'PUB_KEY (Optional)', 'PRIV_KEY (Optional)', '-- FLAGS (Optional)'] [['NAME', 'CREATOR (Optional)', 'PUB_KEY (Optional)', 'PRIV_KEY (Optional)', '-- FLAGS (Optional)'] ...]
                        create an EOSIO account with initial resources using "cleos system newaccount" command. Optional flags are of the form: "-- --buy-ram-bytes 3000"
  --create-cmake-app ['PROJ_NAME', 'DIR'] ['PROJ_NAME', 'DIR']
                        create a smart contract project at from a specific host location
  --create-bare-app ['PROJ_NAME', 'DIR'] ['PROJ_NAME', 'DIR']
                        create a smart contract project at from a specific host location

(...)
  --deploy ['DIR', 'ACCOUNT'] ['DIR', 'ACCOUNT']
                        deploy a smart contract and ABI to account given
(...)
  --send-action ['ACCOUNT', 'ACTION', 'DATA', 'PERMISSION'] ['ACCOUNT', 'ACTION', 'DATA', 'PERMISSION'] ['ACCOUNT', 'ACTION', 'DATA', 'PERMISSION'] ['ACCOUNT', 'ACTION', 'DATA', 'PERMISSION']
                        send action to account with data given and permission
  --get-table ['ACCOUNT', 'SCOPE', 'TABLE'] ['ACCOUNT', 'SCOPE', 'TABLE'] ['ACCOUNT', 'SCOPE', 'TABLE']
                        get the data from the given table
```
which are incorrect in terms of number of arguments, because you can't run i.e. `dune --deploy /home/dir1 eosio /home/dir2 eosio`
They all are caused by incorrect `nargs` usage.
Probably validation has to be added for each of those options.

Possible solutions
- use subparsing: https://docs.python.org/3/library/argparse.html#sub-commands
- for each argument create separate arg parse option, i.e. `--system-newaccount-name NAME --system-newaccount-creator CREATOR --system-newaccount-pub-key PUB_KEY --system-newaccount-priv-key PRIV_KEY`

**Comment by ScottBailey** [comment]
This issue exists for multiple CLI arguments.

**Comment by jolly-fellow** [comment]
IMHO instead of fix this exact problem it would be better to redesign the whole interface while it is not too late and there are no other software dependent on DUNE. The new interface should be hierarchical and grouped by commands and their arguments like the antler-proj.  IMHO such reformatting of the interface will take comparable time with try to fix all problems which gives chaotic set of parameters as it is now. Because parsing of the command line will be much easier and number of the parameters will decrease.

**Comment by jolly-fellow** [comment]
Here is my description of DUNE's CLI parser problems and proposal how to solve them all https://github.com/AntelopeIO/DUNE/issues/129

**Comment by BenjaminGormanPMP** [comment]
Per 3/28/23 Stand-up meeting. 
Escalation – @larryk85 to confirm issue #123 can be postponed.

**Comment by jolly-fellow** [comment]
> Per 3/28/23 Stand-up meeting. Escalation – @larryk85 to confirm issue #123 can be postponed.

I don't ask to postpone it I ask to make decision what should I do:
1. I will make a PR to the fast solution as described. It shouldn't take more than one day.
2. I will rewrite the whole parser. I don't know how much it takes.
3. I will postpone fixing of this bug and all which takes to the CLI interface and switch to something else if there are tasks with higher priority.
