### ISSUE TITLE
Wrap ANTLER Proj in DUNE

### ISSUE THREAD

**Issue by stephenpdeos** [AntelopeIO/DUNE#124]
This should create the commands:

`--create-project` this should take a path, a name and a version (or whatever antler-proj requires)
`--add-app` this should take any pertinent options that `add app` uses 
`--add-lib` this should take any pertinent options that `add lib` uses
`--add-dep` this should take any pertinent options that `add dependency` uses
`--remove-app` this should take any pertinent options that `remove app` uses
`--remove-lib` this should take any pertinent options that `remove lib` uses
`--remove-dep` this should take any pertinent options that `remove dependency` uses
`--update-app` this should take any pertinent options that `update app` uses
`--update-lib` this should take any pertinent options that `update lib` uses
`--build-project` this should take a path to a project
`--clean-build-project` this should remove the build directory and rebuild the project

**Comment by mikelik** [comment]
From Bucky:
Implement the DUNE wrapper for antler-proj tool. It is not currently in CDT, so one thing you can do is add the clone and checkout of larryk85/proj_changes branch and then cmake (...) and build in the dockerfile for DUNE to have it available to use.

For the DUNE side of things, all the functionality you will need should be available as the commands you create won't care about the internal details.
