### ISSUE TITLE
Finalize integration of `antler-proj`

### ISSUE THREAD

**Issue by ScottBailey** [AntelopeIO/DUNE#134]
#127 adds initial integration of `antler-proj` to DUNE; however, no releases are available for it at this time. This issue is written to address that shortcoming.

Please fix the following items:
- Add  `antler-proj` download.  See `bootstrap_cdt.sh` and `bootstrap_leap.sh` for examples.
- Add version selection and display:
  - Update ` --version-all` to display antler-proj version.
  - Add `--antler-proj ANTLER_PROJ_VERSION` to select antler-proj version.
- Test, verify, and correct any issues missed in #127.

Acceptance criteria:
- antler-proj is automatically installed in the container.
- Automated test `tests/test_antler_proj.py` passes.
- `--version all` displays antler-proj info.
- `--antler-proj` changes the installed version.

**Comment by stephenpdeos** [comment]
Because antler-proj will always be part of CDT and adopt it's versioning, this issue is no longer needed.
