### ISSUE TITLE
Modify installation steps on Windows if Docker is already installed

### ISSUE THREAD

**Issue by mikelik** [AntelopeIO/DUNE#140]
From @lparisc:
If we're going to continue to support Dune for windows using chocolatey (the other option is to support it using the WSL linux version), then it's important to warn the user during the install to skip the docker installation if Docker is already installed by using the option that prompts the user to install (y/n) every dependency. Otherwise, it will corrupt the current Docker installation.

As part of the fix:
1. Verify that installing Docker by Chocolatey if it is already installed corrupts Docker
2. Modify installation steps in README.md

Note: this may not be testable in a virtual machine. It may only be testable on native Windows.

**Comment by stephenpdeos** [comment]
Related to https://github.com/AntelopeIO/DUNE/issues/202
