### ISSUE TITLE
Add descriptions of the commands of integrated antler-proj

### ISSUE THREAD

**Issue by jolly-fellow** [AntelopeIO/DUNE#164]
Add descriptions of the commands of integrated antler-proj to the DUNES documentation and to the tutorial: https://github.com/eosnetworkfoundation/docs/blob/main/docs/20_smart-contracts/10_getting-started/10_dune-guide.md

**Comment by mikelik** [comment]
This might be moved here: https://github.com/eosnetworkfoundation/docs/issues

**Comment by jolly-fellow** [comment]
> This might be moved here: https://github.com/eosnetworkfoundation/docs/issues

May be it make sense create one more issue there but this issue is actual anyway because DUNES documentation should be updated too. For example README.md file.

**Comment by stephenpdeos** [comment]
@nsjames can we create a duplicate issue for DevRel to close this out within this repo?

**Comment by stephenpdeos** [comment]
Nvm, found it https://github.com/eosnetworkfoundation/devrel/issues/293
