### ISSUE TITLE
Python files use a weird 3-spaces indentation level

### ISSUE THREAD

**Issue by wackou** [AntelopeIO/DUNE#31]
My editor complains about every line, and this is a very non-standard indentation for python files.

Is this something that you would accept a PR for? and more generally a PR towards PEP-8 compliance? If yes, then I'd be more than willing to contribute it, otherwise feel free to close this issue.

Thanks!

**Comment by stephenpdeos** [comment]
Should be resolved by https://github.com/AntelopeIO/DUNE/issues/37

**Comment by stephenpdeos** [comment]
@wackou thanks for this contribution, one of our new team members is tackling this as one of their first issues. We would love for you to contribute in the future!

**Comment by wackou** [comment]
Thanks! will certainly contribute in the future, or at least try ;)
Closing as duplicate of #37
