### ISSUE TITLE
can not bootstrap dune

### ISSUE THREAD

**Issue by duyluong1994** [AntelopeIO/DUNE#33]
<img width="969" alt="image" src="https://user-images.githubusercontent.com/32863299/194233377-1d4b3cb0-f2fb-4e32-8b99-8010dded0091.png">
Getting this error, I'm using mac M1 and I also can't build Antelope/cdt  so decide to use DUNE but stuck here.

**Comment by stephenpdeos** [comment]
@duyluong1994 do you have any steps to reproduce that you can share? It looks like your issue is that your app update just failed. Thanks!

**Comment by duyluong1994** [comment]
I only cloned DUNE, Add DUNE to PATH then run bootstrap.sh

**Comment by jolly-fellow** [comment]
@duyluong1994 I see here used not encrypted HTTP protocol and it seems your ISP changing your HTTP traffic (insert ads or something like this)
It seems we need to switch to HTTPS before do apt-get update. I need to think how to do it correctly. Or may be switch to another basic image of Ubuntu with already configured HTTPS connection to the repositories.

**Comment by mikelik** [comment]
I had the same error.
In my case it helped to execute following command before running bootstrap.sh:
`sudo apt-get update`

**Comment by duyluong1994** [comment]
I solved it by docker prune 
docker system prune --all --force --volumes
