### ISSUE TITLE
Wallet unlock failed when password is given in password prompt.

### ISSUE THREAD

**Issue by sukanta-manna** [AntelopeIO/DUNE#48]
I wanted to unlock my_wallet. It did not work in case 1. But, did work in case 2. Probably, should be working in both the cases.

(Case 1)

 `dune -- cleos wallet unlock --name my_wallet`
password: `PW5JT3TjkRSYa6CtVwTD8tQ87Z4oXwQGyeNiLW5DPfUozBNL15Q8m`

(Case 2)
`dune -- cleos wallet unlock --name my_wallet --password PW5JT3TjkRSYa6CtVwTD8tQ87Z4oXwQGyeNiLW5DPfUozBNL15Q8m`
![duneFR](https://user-images.githubusercontent.com/18344810/200176741-87d10728-bc1e-4310-9743-e3a65789aa36.png)

**Comment by jolly-fellow** [comment]
@sukanta-manna Command of DUNE `"-- "` executes a command line following `"-- "` inside the container as is. `"--password"` is a command of `cleos`. So actually it means that in the container will be executed the following command: `cleos wallet unlock --name my_wallet --password PW5JT3TjkRSYa6CtVwTD8tQ87Z4oXwQGyeNiLW5DPfUozBNL15Q8m`
By description of the command `wallet unlock` there is the only way to send the password to `cleos` - by using `"--password"` key. 
When you send `password: PW5JT3TjkRSYa6CtVwTD8tQ87Z4oXwQGyeNiLW5DPfUozBNL15Q8m` in the second line it is not considered as a part of the command line for execution inside the container. And it doesn't follow the format of the `"--password"` key. 

https://docs.eosnetwork.com/leap/latest/cleos/command-reference/wallet/unlock

**Comment by stephenpdeos** [comment]
Closing due inactivity
