### ISSUE TITLE
M1 Mac OS wallet export issue

### ISSUE THREAD

**Issue by larryk85** [AntelopeIO/DUNE#5]
On Mac OS, because of file permission issues the wallet is not able to be exported.

This needs some discussion as to whether the ultimate fix should occur in cleos.

**Comment by ericpassmore** [comment]
More likely a MacOS issue, Seeing the same in intel macbook running Monterey os.

**Comment by stephenpdeos** [comment]
Currently there is a workaround for this, but further discussion is needed about where in the codebase we should make the fix.

**Comment by stephenpdeos** [comment]
@ericpassmore can you add in the workaround to this issue?

**Comment by larryk85** [comment]
In addition, I have an engineer making a set of bug fixes to resolve this issue, so I hope to see that at some point next week.
