### ISSUE TITLE
Defects in `--start`

### ISSUE THREAD

**Issue by ScottBailey** [AntelopeIO/DUNE#54]
DUNE start does not behave as described. Here is the relevant help text (from `dune --help`):
```
--start ['NODE', 'CONFIG-DIR (Optional)'] [['NODE', 'CONFIG-DIR (Optional)'] ...]
                        start a new node with a given name and an optional config.ini
```
Given the command `dune --start a b c` it's unclear what dune should do.

I believe this should be corrected to the following help text:
```
--start ['NODE', 'CONFIG-DIR (Optional)']
                        start a new node with a given name and optional path (containing config.ini); 
                        if multiple start options are given, only the last one is used.
```

Additionally, if  the optional path was included and `<CONFIG-DIR>/config.ini` does NOT exist, an error should be returned.

Finally, CONFIG-DIR is not honored and must be fixed.

**Comment by jolly-fellow** [comment]
I see this design problem takes to --create-account key too. It has similar optional parameters which can't be recognized correctly.
