### ISSUE TITLE
--remove <file> should return error when <file> does not exist

### ISSUE THREAD

**Issue by ScottBailey** [AntelopeIO/DUNE#55]
`--remove <file>` should return some non-zero error when `<file>` does not exist.

**Comment by ScottBailey** [comment]
Discussion: should return codes be zero/non-zero or should they be more complex. For example: -1 indicates unknown error, -2 indicates node did not exists, -3 indicates failed to stop node, etc.

**Comment by jolly-fellow** [comment]
> Discussion: should return codes be zero/non-zero or should they be more complex. For example: -1 indicates unknown error, -2 indicates node did not exists, -3 indicates failed to stop node, etc.

IMHO it make sense to add a list of exit codes but register there only 0 for success and 1 for general error. If we will need to add new exit codes in the future it will be easy to add in the existing set.
