### ISSUE TITLE
Internal Tool Versioning, Dynamic Updates, and Packages

### ISSUE THREAD

**Issue by larryk85** [AntelopeIO/DUNE#61]
- [ ] DUNE should allow for multiple versions of `cdt` and `leap` programs to exist in the system at one time and allow the user to be able to select which versions of these they want to be "active".

- [ ] DUNE should be available via a package instead of relying on git clone, so we can install and update dynamically.
- [ ] DUNE should allow for dynamic updates that do not require the end-user to git pull the repo, which will dynamically update internal versions of the tools needed.

**Comment by jolly-fellow** [comment]
IMHO it would be nice to install DUNE and Docker Desktop together and set up Docker Desktop settings in process of the installation. (like adding root directory of the host system to list of shared dirs of the installed Docker Desktop). DUNE will not works with the Docker Engine where namespace remapping is turned off by default. So to avoid complains from user who try to run DUNE on Docker Engine or wrong configured Docker Desktop it make sense to do all settings during the installation process.

**Comment by jolly-fellow** [comment]
And IMHO installation of the image should be done from a prebuilt image placed on Docker Hub or GitHub Container instead of building the image during the installation. It make sense use this image for CI purposes too.

**Comment by mikelik** [comment]
> * [ ]  DUNE should allow for multiple versions of `cdt` and `leap` programs to exist in the system at one time and allow the user to be able to select which versions of these they want to be "active".

I know we were talking that we should choose CDT/leap version when running `dune` command.
However I think it will be easier and simpler if we choose CDT/leap version when running `bootstrap.sh` / `docker build` command.
This way docker image will contain only specified versions of CDT/leap at one time.

I.e. user will be able to run: `bootstrap.sh --leap=3.1.1 --cdt=3.0.0`
or directly docker build:
`docker build --build-arg USER_ID=0 --build-arg GROUP_ID=0 --build-arg CDT_VERSION=3.0.0 --build-arg LEAP_VERSION=3.1.1 -f Dockerfile.unix -t dune`

> * [ ]  DUNE should be available via a package instead of relying on git clone, so we can install and update dynamically.

I see it that way:
1. User downloads docker image, i.e. `docker pull ghcr.io/AntelopeIO/dune:latest`
2. User runs the container with `docker run` command (as there is no `bootstrap.sh` script):
`docker run -p 8888:8888 -p 9876:9876 -p 8080:8080 -p 3000:3000 -p 8000:8000 -v /:/host -d --name=dune_container dune:latest`

Btw, as of today user can download dune image from my personal account: `docker pull ghcr.io/mikelik/dune:latest`
 
> * [ ]  DUNE should allow for dynamic updates that do not require the end-user to git pull the repo, which will dynamically update internal versions of the tools needed.

To download the latest docker image (with the newest CDT/leap version) it should be enough to download image again:
`docker pull ghcr.io/AntelopeIO/dune:latest`

@larryk85 are you fine with above approach?

**Comment by mikelik** [comment]
After yesterday talk I'm updating with more details.

> I know we were talking that we should choose CDT/leap version when running `dune` command. However I think it will be easier and simpler if we choose CDT/leap version when running `bootstrap.sh` / `docker build` command. This way docker image will contain only specified versions of CDT/leap at one time.

Above is nice to have.
The scenario we want to cover is that the client will have their DUNE installed and running with specific version and they will want to upgrade or change leap/cdt to specific version without starting from scratch.
So we want 'dune' command to support settings cdt/leap to specific version.

>     1. User downloads docker image, i.e. `docker pull ghcr.io/AntelopeIO/dune:latest`
>     2. User runs the container with `docker run` command (as there is no `bootstrap.sh` script):
>        `docker run -p 8888:8888 -p 9876:9876 -p 8080:8080 -p 3000:3000 -p 8000:8000 -v /:/host -d --name=dune_container dune:latest`

What we want is that user would like to have above command wrapped in a script (probably 'dune') which will download the newest docker image and run it.
Because of this we want to release DUNE as packages: i.e. rpm, deb, zip or using homebrew or chocolatey.
DUNE scripts would need to be installed in /usr/opt/ - similarly to CDT currently.

> To download the latest docker image (with the newest CDT/leap version) it should be enough to download image again: `docker pull ghcr.io/AntelopeIO/dune:latest`

"docker pull" should be handled by "dune" script.
User will be able to update their DUNE (containing python scripts, i.e. dune.py) by downloading newest DUNE from releases.

**Comment by mikelik** [comment]
DUNE image published as 1.0.0 / latest here https://github.com/orgs/AntelopeIO/packages/container/package/dune
