### ISSUE TITLE
Extension System

### ISSUE THREAD

**Issue by larryk85** [AntelopeIO/DUNE#62]
As we move into the future, more and more functionality will be required.  DApp specific functionality might be needed, EOS specific functionality is already needed.

To solve this problem an extension or module system will be created to allow external projects to create 'modules' to be used to extend the functionality of core DUNE.

**Comment by jolly-fellow** [comment]
As I guess these modules or extensions mean a plugin system which adds new functionality without changing existing code of DUNE?
Generally I'm not sure that DUNE needs for a plugin system to extend its functionality on this stage of development. DUNE was not designed to be extendable by plugins but it is written on Python which allows easily add new code to the project and its design allow easily add new functionality to existing code. I guess in nearest future DUNE will be in state of active development, and extending of its functionality via plugins make development more complicated than direct extending of existing code. 

If it needs to add plugins anyway IMHO they should implement independent functionality which doesn't need to change something inside of core code of DUNE. Therefore plugins may receive from DUNE simple high level interface which gives access to the command line parser (to allow plugins to add and process new command line keys) and allow to do the same things with DUNE from the plugin which user can do from command line.

**Comment by stephenpdeos** [comment]
Done and released
