### ISSUE TITLE
bash and zsh autocomplete

### ISSUE THREAD

**Issue by ScottBailey** [AntelopeIO/DUNE#78]
It would be GREAT to have autocomplete functionality for dune!

**Comment by jolly-fellow** [comment]
It make sense but it's takes significant time especially for two shells so IMHO it make sense to implement when interface of DUNE will be stabilized.

**Comment by ScottBailey** [comment]
`zsh` autocompletion can possibly be done with `bashcompinit`. If so, the real effort is testing and documentation of this functionality.

**Comment by charlestonxorg** [comment]
Thats askinig alot tbh

**Comment by ScottBailey** [comment]
> Thats askinig alot tbh

Sure, but it makes using the tool SIGNIFICANTLY easier.
