### ISSUE TITLE
--bootstrap-system-full doesn't work correctly.

### ISSUE THREAD

**Issue by jolly-fellow** [AntelopeIO/DUNE#80]
It stops during deployment of eosio.system contract with error:

docker container exec dune_container cleos --verbose -u http://127.0.0.1:8888/ set contract eosio /app/reference-contracts/build/contracts/eosio.system

Reading WASM from /app/reference-contracts/build/contracts/eosio.system/eosio.system.wasm...
Publishing contract...
error 2022-12-01T16:08:28.440 cleos     main.cpp:4121                 operator()           ] Failed with error: 2 timeout_exception: deadline 2022-12-01T16:08:28.416 exceeded by 9878us 
deadline 2022-12-01T16:08:28.416 exceeded by 9878us 
    {}
    cleos  json.hpp:63 operator()

Reading WASM from /app/reference-contracts/build/contracts/eosio.system/eosio.system.wasm...
Publishing contract...
error 2022-12-01T16:08:28.440 cleos     main.cpp:4121                 operator()           ] Failed with error: 2 timeout_exception: deadline 2022-12-01T16:08:28.416 exceeded by 9878us 
deadline 2022-12-01T16:08:28.416 exceeded by 9878us 
    {}
    cleos  json.hpp:63 operator()

All contracts before this one are deployed correctly.

I increased option max-transaction-time in config.ini file till 5000 but it doesn't give effect.

The same error on another system:

docker container exec dune_container cleos --verbose -u http://127.0.0.1:8888/ set contract eosio /app/reference-contracts/build/contracts/eosio.system

Reading WASM from /app/reference-contracts/build/contracts/eosio.system/eosio.system.wasm...
Publishing contract...
failed transaction: 888b40696a3c7548b4dd5444dac7ef896e2b3e5cff5a12df71f770b477f57a16  <unknown> bytes  <unknown> us
error 2022-12-14T08:23:52.895 cleos     main.cpp:575                  print_result         ] soft_except->to_detail_string(): 3070003 wasm_serialization_error: Serialization Error Processing WASM
env.set_wasm_parameters_packed unresolveable
    {"module":"env","fn":"set_wasm_parameters_packed"}
    nodeos  eos-vm.cpp:77 validate
pending console output: 
    {"console":""}
    nodeos  apply_context.cpp:123 exec_one

And the same on yet another system:

Reading WASM from /app/reference-contracts/build/contracts/eosio.system/eosio.system.wasm...
Publishing contract...
failed transaction: cd3325a53f8cec9b733ad686bb2eb06832113a3d8fca82f441337294c6047a94  <unknown> bytes  <unknown> us
error 2022-11-28T16:45:10.129 cleos     main.cpp:575                  print_result         ] soft_except->to_detail_string(): 3070003 wasm_serialization_error: Serialization Error Processing WASM
env.set_wasm_parameters_packed unresolveable
    {"module":"env","fn":"set_wasm_parameters_packed"}
    nodeos  eos-vm.cpp:77 validate
pending console output: 
    {"console":""}
    nodeos  apply_context.cpp:123 exec_one

**Comment by mikelik** [comment]
After this issue is solve can you check if following tests can be executed: `tests/test_boostrap.py`?
Simply remove this line: https://github.com/AntelopeIO/DUNE/pull/89/files#diff-4ea78e1e37f0c186c8c962756239a81f811aa6c6bbcb53bb731d19b3a8bf86ceR21

**Comment by jolly-fellow** [comment]
> After this issue is solved can you check if following test can be executed: `tests/test_boostrap.py`? Simply remove this line: https://github.com/AntelopeIO/DUNE/pull/89/files#diff-4ea78e1e37f0c186c8c962756239a81f811aa6c6bbcb53bb731d19b3a8bf86ceR21

Yes of course. No problem.
