### ISSUE TITLE
Add a test for DUNE --get-table key to the functional tests

### ISSUE THREAD

**Issue by jolly-fellow** [AntelopeIO/DUNE#81]
When issue #80 will be resolved add a test for --get-table and --bootstrap-system-full keys to the functional tests.

**Comment by mikelik** [comment]
After this task is done can we check if test tests/test_all_options_tested.py can be executed?
To execute the test simply remove this line: https://github.com/AntelopeIO/DUNE/pull/89/files#diff-45f4fca698bd580039e61a2a95cbd1089d887fb84bbedf04ca51e8aa3d3defa5R14

**Comment by jolly-fellow** [comment]
> After this task is done can we check if test tests/test_all_options_tested.py can be executed? To execute the test simply remove this line: https://github.com/AntelopeIO/DUNE/pull/89/files#diff-45f4fca698bd580039e61a2a95cbd1089d887fb84bbedf04ca51e8aa3d3defa5R14

I have it tested. It works correctly, as I understand. It found following keys:
Missing option: --bootstrap-system
Missing option: --activate-feature
Missing option: --version-all
Missing option: --upgrade
Missing option: --leap
Missing option: --cdt

**Comment by mikelik** [comment]
> I have it tested. It works correctly, as I understand. It found following keys: Missing option: --bootstrap-system Missing option: --activate-feature Missing option: --version-all Missing option: --upgrade Missing option: --leap Missing option: --cdt

Ok, thanks.
We should create a separate issue to cover missing options.
However I'm not sure if testing i.e. argument `--leap` which downloads specific version of leap makes sense.
Maybe we should add some "ignore list" in `test_all_options_tested.py` so we are aware that testing them is not in scope of functional testing.

**Comment by jolly-fellow** [comment]
> > I have it tested. It works correctly, as I understand. It found following keys: Missing option: --bootstrap-system Missing option: --activate-feature Missing option: --version-all Missing option: --upgrade Missing option: --leap Missing option: --cdt
> 
> Ok, thanks. We should create a separate issue to cover missing options. However I'm not sure if testing i.e. argument `--leap` which downloads specific version of leap makes sense. Maybe we should add some "ignore list" in `test_all_options_tested.py` so we are aware that testing them is not in scope of functional testing.

Actually I don't understand why a user may wants to work with several versions of leap. :)
But definitely there are options which don't need for tests. I even added their list with explanation from Bucky to a comment to a test file, but it seems somebody removed it. 
As an option may be to remove this script at all?

**Comment by mikelik** [comment]
> As an option may be to remove this script at all?

This "test" is actually an information for developer what is untested. Maybe we can live it as ignored. Developer can run it anytime.

**Comment by jolly-fellow** [comment]
> > As an option may be to remove this script at all?
> 
> This "test" is actually an information for developer what is untested. Maybe we can live it as ignored. Developer can run it anytime.

Of course. May be it would be useful to add there printing of info about test of which key is placed in which file? Sometimes I'm tired to open files one by one to find needed implementation. 
This is just my personal wish, it is not important.
