### ISSUE TITLE
Is it possible to use API after node start using DUNE ?

### ISSUE THREAD

**Issue by messman1** [AntelopeIO/DUNE#83]
Hi, everyone
I want to use API after node start.
this is my node status. 
![image](https://user-images.githubusercontent.com/48234390/206960351-ba30c6d0-4803-44d7-ae68-1c56c46562a0.png)

and I want to contact my node by API mothod (after making account: host)
curl -X POST -H "Content-Type: application/json; charset=utf-8" -d '{"account_name":"host"}' http://127.0.0.1:8888/get_account

and I got message like this...

curl: (56) Recv failure

is this possible to use API ?
 
thanks

**Comment by jolly-fellow** [comment]
Hello @messman1 please try to do like this:
dune -- curl -X POST -H "Content-Type: application/json; charset=utf-8" -d '{"account_name":"myaccount"}' http://127.0.0.1:8888/v1/chain/get_account

**Comment by messman1** [comment]
It works!!!
thank you jolly!!
