### ISSUE TITLE
Create Chocolatey account and push DUNE package to global repository

### ISSUE THREAD

**Issue by mikelik** [AntelopeIO/DUNE#95]
As a DUNE user I would like to install DUNE on Windows easily.

Currently we build local Chocolatey packages and publish them (or will publish) on github with DUNE releases.
This is a bad practice and we should create [AntelopeIO account](https://community.chocolatey.org/account/Register) and push out our DUNE Chocolatey package there.
This will cause that DUNE will be available for everyone using Chocolatey without downloading DUNE releases from github.
More information about local packages issue [can be found here](https://docs.chocolatey.org/en-us/troubleshooting#package-not-installed.an-error-occurred-during-installation-unable-to-resolve-dependency).

Additionally it will allow to add dependencies to DUNE i.e. python3 or docker like in below commit:
https://github.com/AntelopeIO/DUNE/commit/1e5b6499926600bcd01cdc8e8de09fd100bbdf3e

Prerequisite:
- [x] access to shared / common ENF mailbox (i.e. support@eosnetworks.com)

**Comment by jolly-fellow** [comment]
May be it would be easier if you register the account to your email and when the installation will be tested and ready for using you switch it to an official email?

**Comment by mikelik** [comment]
It seems developers already have access to support@eosnetwork.com - https://groups.google.com/a/eosnetwork.com/g/support?hl=en so it shouldn't be a problem.
