### ISSUE TITLE
No DUNE nupkg file is found at the latest release page.

### ISSUE THREAD

**Issue by kostia-ivashchenko** [AntelopeIO/DUNE#97]
In the description of DUNE installation on Windows it is demanded: "From the [latest release](https://github.com/AntelopeIO/DUNE/releases/latest) page, download latest DUNE nupkg".
But there is no `*.nupkg` file on the latest release page,

**Comment by mikelik** [comment]
Hi @kostia-ivashchenko,
we haven't released the newest DUNE yet. Temporarily can you please go and try steps from https://github.com/AntelopeIO/DUNE/pull/96#issue-1518626403?

**Comment by kostia-ivashchenko** [comment]
> Hi @kostia-ivashchenko, we haven't released the newest DUNE yet. Temporarily can you please go and try steps from [#96 (comment)](https://github.com/AntelopeIO/DUNE/pull/96#issue-1518626403)?

I can. But IMHO it reasonable to move the description from the comment to README.md.

**Comment by mikelik** [comment]
> > Hi @kostia-ivashchenko, we haven't released the newest DUNE yet. Temporarily can you please go and try steps from [#96 (comment)](https://github.com/AntelopeIO/DUNE/pull/96#issue-1518626403)?
> 
> I can. But IMHO it reasonable to move the description from the comment to README.md.

Yes, it is done now.
Thanks for testing!
