### ISSUE TITLE
'Workspace' is not formally defined in README.md

### ISSUE THREAD

**Issue by kostia-ivashchenko** [AntelopeIO/DUNE#98]
Chapter "Concept and operations" in README.md contains the phrase that is started with "The drive/directory that your workspace is in ...". In the meantime it is not defined before what 'workspace' exactly is, whether it is possible to change it, etc. It makes further explanations quite fuzzy, especially for Windows, where disk drives rather than only folder names are involved.

For example, I get the following message:
```
PS D:\~Blockchain\WAX\DUNE> dune --create-cmake-app hello ./
/host/~Blockchain/WAX/DUNE path not found

Internal Error
```
And I do not know how to avoid it,

**Comment by mikelik** [comment]
@kostia-ivashchenko 
is this issue still happening?
I created similar directory structure and it worked properly. Possibly something was fixed already since you raised the issue:
```
PS C:\~Blockchain\WAX\DUNE> dune --create-cmake-app hello ./
PS C:\~Blockchain\WAX\DUNE> dir


    Directory: C:\~Blockchain\WAX\DUNE


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        23.02.2023     11:04                hello


PS C:\~Blockchain\WAX\DUNE> cd hello
PS C:\~Blockchain\WAX\DUNE\hello> dir


    Directory: C:\~Blockchain\WAX\DUNE\hello


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        23.02.2023     11:04                build
d-----        23.02.2023     11:04                include
d-----        23.02.2023     11:04                ricardian
d-----        23.02.2023     11:04                src
-a----        23.02.2023     11:04            442 CMakeLists.txt
-a----        23.02.2023     11:04            462 README.txt

```

**Comment by mikelik** [comment]
From @nsjames: issue happens when the DUNE working directory (workspace) is on another drive than C:\
Reopening

**Comment by stephenpdeos** [comment]
We'll spend a few more cycles on this, but if we cannot resolve we will at least update documentation for Windows to specify only installing on C: supported
